export type StudioRealityMode = 'human' | 'restaurant' | 'menu' | 'luxury' | 'finalBoss';
export type StudioBackgroundPresetId =
  | 'wood-table'
  | 'marble-table'
  | 'pickup-counter'
  | 'open-kitchen'
  | 'window-booth'
  | 'delivery-packaging'
  | 'busy-dining-blur'
  | 'neutral-menu';

export const STUDIO_FORBIDDEN_REALITY_OBJECTS = [
  'دلة', 'دلال', 'مبخر', 'مباخر', 'بخور', 'عود', 'سدو', 'فانوس', 'فوانيس',
  'dallah', 'arabic coffee pot', 'incense', 'bukhoor', 'oud burner', 'sadu', 'lantern'
];

export const STUDIO_REALITY_NEGATIVE_PROMPT = `STRICT REALITY BAN: no dallah, no Arabic coffee pot, no incense, no bukhoor, no oud burner, no sadu patterns, no lanterns, no fake heritage props, no fantasy restaurant, no palace, no CGI, no 3D render, no plastic food, no floating objects, no fake smoke, no neon overkill, no text, no letters, no logos, no watermark. Keep all backgrounds believable, ordinary, human-photographed, and restaurant-real.`;

export const RESTAURANT_REALITY_POLICY = `
HUMAN RESTAURANT REALITY POLICY:
- The image must feel photographed by a real human in a real restaurant, not generated by AI.
- Use believable restaurant elements only: table surface, chair edge, booth, counter, pickup shelf, glass wall, kitchen stainless steel, napkin, water cup, receipt tray, neutral wall, soft bokeh.
- Avoid perfect symmetry, fantasy decor, palace interiors, exaggerated luxury, fake Kuwaiti heritage props, artificial smoke, and over-polished CGI surfaces.
- Use natural lens behavior: 35mm or 50mm perspective, mild depth of field, slight lens softness, correct scale, believable shadows, realistic reflections, and ordinary imperfections.
- Keep empty clean areas for overlay/logo without creating text inside the generated image.
- IMPORTANT: ABSOLUTELY NO TEXT, NO LETTERS, NO WORDS, NO LOGOS, NO SIGNATURES, NO WATERMARKS ANYWHERE INSIDE THE GENERATED IMAGE.
`;

export const PRODUCT_LOCK_POLICY = `
LOCK THE FOOD PRODUCT:
- Keep the original dish/plate/bowl exactly recognizable: same food, same plate, same garnish, same sauce, same portion, same edges, same color identity.
- Do not invent ingredients. Do not replace the plate. Do not add/remove toppings. Do not change the recipe.
- Allowed improvements only: cleaner crop, gentle edge cleanup, realistic lighting integration, believable shadows, background replacement, table surface, depth of field.
- Treat the dish as a real photographed object placed into a real restaurant environment.
`;

export const STUDIO_REALITY_MODES: Record<StudioRealityMode, { label: string; prompt: string }> = {
  human: {
    label: 'تصوير بشري / آيفون',
    prompt: 'Style: believable iPhone-style restaurant photo, handheld human framing, natural indoor light, slight imperfection, realistic colors, no studio perfection.'
  },
  restaurant: {
    label: 'مطعم حقيقي',
    prompt: 'Style: real dine-in restaurant photography, believable table scene, warm ambient restaurant lighting, practical background, real-world Kuwait modern restaurant feel without heritage props.'
  },
  menu: {
    label: 'منيو احترافي',
    prompt: 'Style: professional menu photography, clean table surface, controlled soft light, product remains true, realistic shadows, commercial but still photographed not rendered.'
  },
  luxury: {
    label: 'إعلان بشري فاخر',
    prompt: 'Style: premium human-shot food ad, elegant but believable restaurant interior, restrained luxury, natural materials, no fantasy decor, no CGI gloss.'
  },
  finalBoss: {
    label: 'Reality Final Boss',
    prompt: 'Style: ultra-believable human restaurant photography. The scene must pass as a real photo taken on location: imperfect handheld framing, real lens softness, grounded scale, believable shadows, ordinary restaurant surfaces, no AI polish, no fantasy styling.'
  }
};

export const REAL_RESTAURANT_BACKGROUNDS: Record<StudioBackgroundPresetId, { label: string; prompt: string }> = {
  'wood-table': {
    label: 'طاولة خشب مطعم',
    prompt: 'Background: real medium-dark wooden restaurant table, blurred chair edge, small napkin, soft warm overhead restaurant light, ordinary believable dine-in setup.'
  },
  'marble-table': {
    label: 'رخام أبيض هادئ',
    prompt: 'Background: real white or off-white marble table in a modern casual restaurant, subtle reflection, neutral wall blur, realistic shadows and scale.'
  },
  'pickup-counter': {
    label: 'كاونتر استلام',
    prompt: 'Background: real pickup counter area in a restaurant, stainless edge or neutral counter, faint blurred shelves, practical takeout environment, no fake signage or text.'
  },
  'open-kitchen': {
    label: 'مطبخ تحضير حقيقي',
    prompt: 'Background: real open kitchen pass, stainless steel, soft bokeh, practical prep area, clean but not perfect, believable restaurant workflow without visible text.'
  },
  'window-booth': {
    label: 'جلسة قرب الزجاج',
    prompt: 'Background: real booth/table near a glass window, natural daylight, blurred street or storefront feeling, realistic restaurant depth, no readable signs.'
  },
  'delivery-packaging': {
    label: 'توصيل وسفري',
    prompt: 'Background: realistic takeout/delivery setup, plain packaging, paper bag, counter or table surface, human everyday commercial feel, no fake branding text.'
  },
  'busy-dining-blur': {
    label: 'مطعم مشغول Blur',
    prompt: 'Background: softly blurred busy dining area with indistinct people silhouettes only, no identifiable faces, warm lights, realistic distance and depth.'
  },
  'neutral-menu': {
    label: 'خلفية منيو نظيفة',
    prompt: 'Background: neutral professional menu-photo setup, matte table surface, simple real wall, controlled soft shadows, no props except minimal napkin/cutlery if needed.'
  }
};



export const REALITY_FINAL_BOSS_POLICY = `
REALITY FINAL BOSS OVERRIDE:
- Make the result boringly believable before making it beautiful. Real restaurant first, advertisement second.
- Avoid the common AI tells: over-perfect lighting, glossy fake tabletops, unreal depth blur, empty luxury halls, decorative clutter, duplicated objects, floating props, and cinematic smoke.
- Use one specific ordinary location: a real dine-in table, pickup counter, window booth, open kitchen pass, delivery counter, or clean menu table.
- Add tiny human-camera imperfections: slight off-axis angle, real contact shadows, uneven napkin/cup placement, realistic table wear, practical indoor restaurant light.
- If unsure, choose a simpler real background rather than a dramatic one.
`;

export const STRICT_PLATE_LOCK_POLICY = `
STRICT PLATE LOCK:
- The original plate/bowl and the food identity are sacred. Do not swap the plate, change the food shape, change toppings, invent sauces, add garnish, or remove parts.
- Preserve the original dish silhouette and portion. Only clean the visible crop/edges and blend it into a believable table/environment.
- Background, light, shadow, lens, and table are allowed to change. Food construction is not.
`;

export const REALITY_AUDIT_RUBRIC = `
REALITY AUDIT RUBRIC:
Evaluate whether the image looks like a human restaurant photo. Check: believable background, correct dish preservation, natural shadows, realistic scale, lens behavior, no AI/fantasy decor, no text/logos inside image, no forbidden heritage props.
Return concise Arabic notes and a 0-100 realism score.
`;

export const buildProductRealityPrompt = ({ theme, mood, mode, background }: { theme?: string; mood?: string; mode?: StudioRealityMode; background?: StudioBackgroundPresetId }) => {
  const modePrompt = STUDIO_REALITY_MODES[mode || 'restaurant']?.prompt || STUDIO_REALITY_MODES.restaurant.prompt;
  const backgroundPrompt = REAL_RESTAURANT_BACKGROUNDS[background || 'wood-table']?.prompt || REAL_RESTAURANT_BACKGROUNDS['wood-table'].prompt;
  return `${PRODUCT_LOCK_POLICY}\n${STRICT_PLATE_LOCK_POLICY}\n${RESTAURANT_REALITY_POLICY}\n${REALITY_FINAL_BOSS_POLICY}\n${modePrompt}\n${backgroundPrompt}\nUser theme: ${theme || 'مطعم واقعي'}. Mood: ${mood || 'دافئ'}.\n${STUDIO_REALITY_NEGATIVE_PROMPT}`;
};

export const buildTextRealityPrompt = (purpose: string, subject: string, formatHint = '') => `${RESTAURANT_REALITY_POLICY}\n${REALITY_FINAL_BOSS_POLICY}\nPurpose: ${purpose}.\nSubject: ${subject}.\n${formatHint}\nChoose one believable real restaurant location from the internal library: wooden table, marble table, pickup counter, open kitchen pass, window booth, delivery packaging, busy dining blur, or neutral menu setup. Build the image as a plausible human photo for a real restaurant in Kuwait: ordinary table/counter/window/kitchen context, natural scale, practical lighting, no fake event props. The final image must make viewers ask where it was photographed, not which AI made it.\n${STUDIO_REALITY_NEGATIVE_PROMPT}`;
